# check-status.yml
---
  - hosts: webservers:loadbalancer
    become: true
    tasks:
      - name: Check status of apache
        shell: 
          cmd: service apache2 status
          warn: False